// +build js,wasm

/*
DO NOT EDIT

Code automatically generated by github.com/PapaCharlie/go-jsapi
*/
package jsapi

import js "syscall/js"

type ArbitraryObject js.Value

func (wrapper *ArbitraryObject) SetInnerHTML(value string) {
	(*js.Value)(wrapper).Set("innerHTML", value)
}

func (wrapper *ArbitraryObject) GetInnerHTML() string {
	return (*js.Value)(wrapper).Get("innerHTML").String()
}
