// +build js,wasm

/*
DO NOT EDIT

Code automatically generated by github.com/PapaCharlie/go-jsapi
*/
package jsapi

import js "syscall/js"

type Canvas js.Value

func (wrapper *Canvas) SetWidth(value float64) {
	(*js.Value)(wrapper).Set("width", value)
}

func (wrapper *Canvas) GetWidth() float64 {
	return (*js.Value)(wrapper).Get("width").Float()
}

func (wrapper *Canvas) SetHeight(value float64) {
	(*js.Value)(wrapper).Set("height", value)
}

func (wrapper *Canvas) GetHeight() float64 {
	return (*js.Value)(wrapper).Get("height").Float()
}
